version: '3.3'

networks:
  web:
    external: true
  stack:
    external: false

volumes:
  database:

services:
  tooling:
    build:
      context: .
      dockerfile: ./docker/tooling/Dockerfile
      args:
        USER_ID: $USER_ID
        GROUP_ID: $GROUP_ID
    networks:
      - stack
    tty: true
    working_dir: /var/www/html
    volumes:
      - ./docker/tooling/php.ini:/usr/local/etc/php/php.ini:cached
      - ./:/var/www/html
    restart: always
